# Generated by Django 3.0.7 on 2020-06-23 16:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todolist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('başlık', models.CharField(max_length=144, verbose_name='başlık')),
                ('açıklama', models.TextField(blank=True, null=True, verbose_name='açıklama')),
                ('eklenme_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='eklenme_tarihi')),
                ('durum', models.BooleanField(default=False, verbose_name='yapıldı')),
            ],
        ),
    ]
