# Generated by Django 2.2.13 on 2020-06-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'Yapılacaklar', 'verbose_name_plural': 'Yapılacaklar'},
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='açıklama',
            new_name='aciklama',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='başlık',
            new_name='baslik',
        ),
    ]
